version: '3'
services:
  go-dev:
    container_name: go-dev
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    tty: true
    environment:
      - TZ=Asia/Tokyo

